app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

easy_admin_bundle:
    # resource: "@EasyAdminBundle/Controller/"
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

rest: 
    type : rest 
    resource: "@AppBundle/Controller/ApiCoreController.php"
    prefix : /api
