fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: admin
    user_class: AppBundle\Entity\Users
    group:
        group_class: AppBundle\Entity\Group